services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app_dev
    command: sh -c "npm run start:dev"
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app_dev
    command: npm run dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
