# Arquivo: docker-compose.yml

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: interview_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do Backend NestJS (para produção)
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3001:3000"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_DATABASE: interview_db
    depends_on:
      - postgres-db

  # Serviço do Frontend React (para produção)
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend

# Declara o volume nomeado para persistência dos dados
volumes:
  postgres_data: